* [t#27] Added checking of required build tools

diff --git a/app/configure b/app/configure
--- a/app/configure
+++ b/app/configure
@@ -57,9 +57,20 @@ fi
 
 ############################
 
+. ../check-tools.in
+
+check_tools $BUILDTOOLS
+if [ $? -eq 127 ]
+then
+  echo "missing required tool. aborting."
+  exit 1
+fi
+
+
 
 #for being seen from openfluid-config script
 export OPENFLUIDSDKPREFIX 
+
 
 
 OPTFILE=makeopts.inc
diff --git a/sdk/configure b/sdk/configure
--- a/sdk/configure
+++ b/sdk/configure
@@ -56,6 +56,14 @@ fi
 
 ############################
 
+. ../check-tools.in
+
+check_tools $BUILDTOOLS
+if [ $? -eq 127 ]
+then
+  echo "missing required tool. aborting."
+  exit 1
+fi
 
 
 
