* Added usage information in configure script * Added compilation flags corresponding to build type in configure script * Modified configure script for better path handling * Added new package target in main makefile for rough package builds

diff --git a/app/src/configure b/app/src/configure
--- a/app/src/configure
+++ b/app/src/configure
@@ -2,14 +2,13 @@
 
 ############################
 
-
-MACHTYPE=i486-pc-linux-gnu
-
-OSTYPE=linux-gnu
-
 CC=gcc
 CPP=g++
 F77=
+
+RELEASE_CCCFLAGS=-O3
+NIGHTLY_CCCFLAGS=
+DEVEL_CCCFLAGS=-g3
 
 SETUPH=sdk/setup.h
 
@@ -54,15 +53,73 @@ MDEF_OUTPUTFILES_EXT=out
 ############################
 
 
+usage_info() {
+  echo "MHYDAS configure script usage:\n"
+  echo "  ./configure [OPTION]\n"
+  echo " available options:"
+  echo "      --release      builds a release version" 
+  echo "      --devel        builds a development version"
+  echo "      --nightly      builds a nightly-build version"
+}
 
 
+if [ "$1" != "--release" ] && [ "$1" != "--devel" ] && [ "$1" != "--nightly" ]; then
+  usage_info
+  exit 1
+fi
+
+
+OPTFILE=makeopts.inc
+
+rm -f $OPTFILE
+rm -f $SETUPH
+
+
+SHELLCMD=/bin/bash
+
+
+if [ -z "$OSTYPE" ]; then
+  if [ -x $SHELLCMD ]; then
+    OSTYPE=`$SHELLCMD -c 'echo \$OSTYPE'`
+  fi
+  if [ -z "$OSTYPE" ]; then
+    echo "unable to determine \$OSTYPE value. aborting."
+    exit 1
+  fi
+fi
+
+if [ "$OSTYPE" != "linux-gnu" ] && [ "$OSTYPE" != "msys" ]; then
+  echo "platform not supported. aborting"
+  exit 1
+fi
+
+
+if [ -z "$MACHTYPE" ]; then
+  if [ -x $SHELLCMD ]; then
+    MACHTYPE=`$SHELLCMD -c 'echo \$MACHTYPE'`
+  fi
+  if [ -z "$MACHTYPE" ]; then
+    echo "unable to determine \$MACHTYPE value. aborting."
+    exit 1
+  fi
+fi
+
+
+BUILDVER=
+case $1 in 
+  "--nightly") BUILDVER="nightly";;   
+  "--devel") BUILDVER="development";;
+esac
+
+
+SVNREV=x
+if [ -x /usr/bin/svnversion ]; then
+  SVNREV=`svn info --revision HEAD | grep "vision :" | cut -d" " -f3 `  
+fi
 
 
 
 # ------------ option file for makefiles -------------
-
-OPTFILE=makeopts.inc
-
 
 if [ "$OSTYPE" = "msys" ]; then
   EXEFILE=$EXEFILEROOT.exe
@@ -77,6 +134,22 @@ else
   PLUGINEXT=sompi
   DYNLIBCCFLAGS=-fPIC
 fi
+
+
+CCCFLAGS=
+
+if [ "$1" = "--release" ]; then 
+  CCCFLAGS=$RELEASE_CCCFLAGS
+fi
+
+if [ "$1" = "--devel" ]; then
+  CCCFLAGS=$DEVEL_CCCFLAGS
+fi
+
+if [ "$1" = "--nightly" ]; then
+  CCCFLAGS=$NIGHTLY_CCCFLAGS
+fi
+
 
 
 echo "# Makefile options generated by configure script." > $OPTFILE
@@ -124,7 +197,7 @@ echo "# common compile options" >> $OPTFILE
 echo "CCCLIBS =" >> $OPTFILE
 
 echo "# common compile flags" >> $OPTFILE 
-echo "CCCFLAGS =" >> $OPTFILE
+echo "CCCFLAGS = $CCCFLAGS" >> $OPTFILE
 
 echo "# dynamic lib compile flags" >> $OPTFILE 
 echo "DYNLIBCCFLAGS = $DYNLIBCCFLAGS" >> $OPTFILE
@@ -145,8 +218,9 @@ echo "PLUGINEXT = $PLUGINEXT" >> $OPTFILE
 
 echo "" >> $OPTFILE
 
-echo "# sdk libs files root" >> $OPTFILE
-echo "SDKLIBSROOT = $SDKLIBSROOT" >> $OPTFILE
+echo "# sdk libs files names" >> $OPTFILE
+echo "SDKLIBBASE = $SDKLIBSROOT-base" >> $OPTFILE
+echo "SDKLIBCORE = $SDKLIBSROOT-core" >> $OPTFILE
 
 echo "" >> $OPTFILE
 
@@ -160,8 +234,17 @@ echo "STALIBEXT = $STALIBEXT" >> $OPTFILE
 
 echo "" >> $OPTFILE
 
+# détermination du chemin absolu de la racine du projet située ../..
+ORIGPATH=`pwd`
+ABSPATH=$ORIGPATH/../..
+cd $ABSPATH
+ABSPATH=`pwd`
+cd $ORIGPATH
+
+
+
 echo "# build base dir" >> $OPTFILE
-echo "BASEBUILDDIR = `pwd`/../../build/$MACHTYPE" >> $OPTFILE
+echo "BASEBUILDDIR = $ABSPATH/build/$MACHTYPE" >> $OPTFILE
 
 echo "# binary dir" >> $OPTFILE
 echo "BASEBINDIR = \$(BASEBUILDDIR)/bin" >> $OPTFILE
@@ -173,14 +256,39 @@ echo "# built libs dir" >> $OPTFILE
 echo "BASELIBDIR = \$(BASEBUILDDIR)/lib" >> $OPTFILE
 
 echo "# built doc dir" >> $OPTFILE
-echo "BASEDOCDIR = `pwd`/../../doc" >> $OPTFILE
+echo "BASEDOCDIR = $ABSPATH/doc" >> $OPTFILE
 
+echo "# packages dir" >> $OPTFILE
+echo "BASEPACKDIR = $ABSPATH/packages/$MACHTYPE" >> $OPTFILE
 
 echo "" >> $OPTFILE
 
-
 echo "# built plugins subdir" >> $OPTFILE 
 echo "PLUGSUBDIR = $PLUGSUBDIR" >> $OPTFILE  
+
+
+echo "# build type" >> $OPTFILE
+echo "BUILDVER = $BUILDVER" >> $OPTFILE
+
+echo "# svn revision value" >> $OPTFILE
+echo "SVNREV = $SVNREV" >> $OPTFILE
+
+
+echo "# package name root" >> $OPTFILE
+if [ "$BUILDVER" = "nightly" ]; then
+  echo "BINPACKNAMEROOT = mhydas-bin-$MAJORVER.$MINORVER-$MACHTYPE-nightly-`date +%Y%m%d`" >> $OPTFILE  
+fi
+
+if [ "$BUILDVER" = "development" ]; then
+  echo "BINPACKNAMEROOT = mhydas-bin-$MAJORVER.$MINORVER-$MACHTYPE-development-$SVNREV" >> $OPTFILE  
+fi
+
+
+if [ -z $BUILDVER ]; then
+  echo "BINPACKNAMEROOT = mhydas-bin-$MAJORVER.$MINORVER-$MACHTYPE" >> $OPTFILE  
+fi
+
+
 
 
 echo "configuration file for compilation generated ($OPTFILE)"
@@ -254,14 +362,6 @@ echo "const wxString MHYDAS_PLUGINS_SUBDIR = wxT(\"$PLUGSUBDIR\");" >> $SETUPH
 echo "" >> $SETUPH
 
 
-BUILDVER=
-if [ $# = 1 ]; then
-  case $1 in 
-    "-nightly") BUILDVER="nighly build";;   
-    "-devel") BUILDVER="development build";
-  esac
-fi
-
 echo "// Version information" >> $SETUPH
 echo "const wxString MAJOR_VERSION = wxT(\"$MAJORVER\");" >> $SETUPH
 echo "const wxString MINOR_VERSION = wxT(\"$MINORVER\");" >> $SETUPH
@@ -269,10 +369,10 @@ echo "const wxString BUILD_VERSION = wxT(\"$BUILDVER\");" >> $SETUPH
 
 echo "" >> $SETUPH
 
-if [ -x /usr/bin/svnversion ]; then
+if [ $SVNREV != "x" ]; then
   echo "// Subversion revision information" >> $SETUPH
   echo "#define SVN_REV" >> $SETUPH
-  echo "const wxString SVN_REVISION = wxT(\"`svn info --revision HEAD | grep "Révision :" | cut -d" " -f3 `\");" >> $SETUPH
+  echo "const wxString SVN_REVISION = wxT(\"$SVNREV\");" >> $SETUPH
   echo "" >> $SETUPH
 fi
 
@@ -289,3 +389,8 @@ echo "" >> $SETUPH
 
 echo "setup file for source code generated ($SETUPH)"
 
+
+# ------------ setup header file for source code -------------
+
+
+exit 0
